[project]
name = ""
version = ""
description = ""
authors = [
    {name = "maoxd", email = "maoxingda@meican.com"},
]
dependencies = [
    "Jinja2",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
