# Generated by Django 4.1 on 2023-10-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SqlFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Sql文件路径')),
                ('etl_start_date', models.DateField(verbose_name='ETL开始时间')),
                ('etl_end_date', models.DateField(verbose_name='ETL结束时间')),
                ('is_delete_comment', models.BooleanField(default=False, verbose_name='是否删除注释')),
            ],
            options={
                'verbose_name': '脚本文件',
                'verbose_name_plural': '脚本文件',
                'ordering': ('path',),
            },
        ),
        migrations.CreateModel(
            name='WorkDir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True, verbose_name='工作目录路径')),
            ],
            options={
                'verbose_name': '工作目录',
                'verbose_name_plural': '工作目录',
            },
        ),
    ]
