# Generated by Django 4.1 on 2023-10-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmcl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlfile',
            name='etl_end_date',
        ),
        migrations.RemoveField(
            model_name='sqlfile',
            name='etl_start_date',
        ),
        migrations.RemoveField(
            model_name='sqlfile',
            name='is_delete_comment',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('etl_start_date', models.DateField(verbose_name='ETL开始时间')),
                ('etl_end_date', models.DateField(verbose_name='ETL结束时间')),
                ('is_delete_comment', models.BooleanField(default=False, verbose_name='是否删除注释')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sql_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmcl.sqlfile', verbose_name='脚本文件')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ('name',),
            },
        ),
    ]
