# Generated by Django 4.1 on 2023-10-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcl', '0002_remove_sqlfile_etl_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlfile',
            name='is_procedure',
            field=models.BooleanField(default=False, verbose_name='是否存储过程'),
        ),
    ]
