# Generated by Django 4.1 on 2023-10-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcl', '0003_sqlfile_is_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_render',
            field=models.BooleanField(default=False, verbose_name='是否已经渲染'),
        ),
    ]
