# Generated by Django 4.1 on 2023-10-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcl', '0004_task_is_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='render_sql_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='渲染后的脚本文件路径'),
        ),
    ]
