# Generated by Django 4.1 on 2023-10-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcl', '0005_task_render_sql_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='render_sql_file',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='渲染后的脚本文件路径'),
        ),
    ]
