# Generated by Django 4.1 on 2023-10-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcl', '0006_alter_task_render_sql_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_render',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否已经渲染'),
        ),
    ]
